---
- hosts: localhost
  user: root
  tasks:
    - name: Build docker image
      command: sudo docker build  -t test .
    - name: Run container from image
      command: sudo docker run -it -d  test
