---
- hosts: localhost
  become: yes
  sudo: yes
  user: ec2-user
  tasks:
    - name: Build docker image
      command: docker build  -t test .
    - name: Run container from image
      command: docker run -it -d  test
